-- Settlement Line (AdjustmentList Pega) pada POOLDATA.T_CLAIM_ADJUSTMENT, tahap InputSurveyor.
--
-- DITULIS modul ini hanya untuk klaim yang dibuat aplikasi ini, sama seperti
-- T_CLAIM_ESTIMASI. Tabel warisan tanpa kunci primer dan tanpa penanda hapus: baris hanya
-- diperbarui atau disisipkan, tidak pernah dihapus (D-66).
--
-- Kuncinya mengikuti PEGA_CONVERT_JSONKLAIM_PNC.prc: OBJECTID objek, OBJECTCOVERAGEID urutan
-- coverage di dalam objek, ADJUSTMENTID urutan baris.
--
-- PROPOSE_VALUE adalah ProposeValue, "Nilai Pengajuan Tertanggung" pada InputAdjustment_sect.
--
-- Satuan: nilai uang dalam rupiah/valuta di kolom, sen di domain; persen (LOC, ASM_SHARE,
-- INDIVIDUAL_RISK_PERCENT) apa adanya di kolom, per 10.000 di domain; kurs per 10.000 di domain.

-- name: adjustment_perbarui
UPDATE POOLDATA.T_CLAIM_ADJUSTMENT
   SET PAYMENTTYPE = :1, CURRENCY = :2, CURRENCYVALUE = :3 / 10000, TOTAL_CLAIM = :4 / 100,
       LOC = :5 / 10000, NILAI_SALVAGE_A = :6 / 100, INDIVIDUAL_RISK_TYPE = :7,
       INDIVIDUAL_RISK_PERCENT = :8 / 10000, INDIVIDUAL_RISK_VALUE = :9 / 100,
       GROSSVALUE = :10 / 100, ASM_SHARE = :11 / 10000, ASM_SHARE_VALUE = :12 / 100,
       NILAIAKSEPTASI = :13 / 100, PROPOSE_VALUE = :14 / 100, EXGRATIA = :15,
       CIRCUMCAUSEOFLOSS = :16, NOTES = :17, STATUSAKSEPTASI = :18, NOAKSEPTASI = :19
 WHERE CLAIMID = :20 AND OBJECTID = :21 AND OBJECTCOVERAGEID = :22 AND ADJUSTMENTID = :23

-- name: adjustment_sisip
INSERT INTO POOLDATA.T_CLAIM_ADJUSTMENT
       (PAYMENTTYPE, CURRENCY, CURRENCYVALUE, TOTAL_CLAIM, LOC, NILAI_SALVAGE_A,
        INDIVIDUAL_RISK_TYPE, INDIVIDUAL_RISK_PERCENT, INDIVIDUAL_RISK_VALUE, GROSSVALUE,
        ASM_SHARE, ASM_SHARE_VALUE, NILAIAKSEPTASI, PROPOSE_VALUE, EXGRATIA, CIRCUMCAUSEOFLOSS,
        NOTES, STATUSAKSEPTASI, NOAKSEPTASI, CLAIMID, OBJECTID, OBJECTCOVERAGEID, ADJUSTMENTID)
VALUES (:1, :2, :3 / 10000, :4 / 100, :5 / 10000, :6 / 100, :7, :8 / 10000, :9 / 100,
        :10 / 100, :11 / 10000, :12 / 100, :13 / 100, :14 / 100, :15, :16, :17, :18, :19,
        :20, :21, :22, :23)

-- name: adjustment_daftar
SELECT OBJECTID, OBJECTCOVERAGEID, ADJUSTMENTID, PAYMENTTYPE, CURRENCY,
       ROUND(CURRENCYVALUE * 10000), ROUND(TOTAL_CLAIM * 100), ROUND(LOC * 10000),
       ROUND(NILAI_SALVAGE_A * 100), INDIVIDUAL_RISK_TYPE, ROUND(INDIVIDUAL_RISK_PERCENT * 10000),
       ROUND(INDIVIDUAL_RISK_VALUE * 100), ROUND(GROSSVALUE * 100), ROUND(ASM_SHARE * 10000),
       ROUND(ASM_SHARE_VALUE * 100), ROUND(NILAIAKSEPTASI * 100), ROUND(PROPOSE_VALUE * 100),
       EXGRATIA, CIRCUMCAUSEOFLOSS, NOTES, STATUSAKSEPTASI, NOAKSEPTASI
  FROM POOLDATA.T_CLAIM_ADJUSTMENT
 WHERE CLAIMID = :1
 ORDER BY OBJECTID, TO_NUMBER(OBJECTCOVERAGEID), TO_NUMBER(ADJUSTMENTID)
