-- 0004 (turun) — mencabut kolom LINEBUSINESS dari M_LOGIN_PNC
--
-- ============================================================================
-- MENJALANKAN INI MENGHAPUS DATA, DAN DATANYA TIDAK DAPAT DIPULIHKAN
-- ============================================================================
--
-- Isi kolom LINEBUSINESS adalah hasil pekerjaan admin yang memetakan setiap pengguna ke
-- lini bisnisnya. Pemetaan itu TIDAK ADA di tempat lain — tidak di export Pega, tidak di
-- tabel lain, tidak di dokumen mana pun (`11-SECURITY.md` §3.1). Menghapus kolomnya
-- berarti menghapus satu-satunya salinan.
--
-- SEBELUM menjalankan, simpan isinya:
--
--   CREATE TABLE POOLDATA.CPNC_LINEBUSINESS_BACKUP AS
--   SELECT LOGIN_ID, LINEBUSINESS, SYSTIMESTAMP AS DISIMPAN_PADA
--     FROM POOLDATA.M_LOGIN_PNC
--    WHERE LINEBUSINESS IS NOT NULL;
--
-- Periksa jumlahnya cocok sebelum melanjutkan:
--
--   SELECT COUNT(*) FROM POOLDATA.CPNC_LINEBUSINESS_BACKUP;
--   SELECT COUNT(*) FROM POOLDATA.M_LOGIN_PNC WHERE LINEBUSINESS IS NOT NULL;
--
--
-- ## Akibat pada aplikasi setelah dicabut
--
-- Layar Inbox Outstanding TETAP BERJALAN. Pembacaan kolomnya gagal dengan ORA-00904, dan
-- kegagalan itu ditangani sebagai "lini tidak diketahui" — yang jatuh ke tanpa batas.
--
-- Artinya SELURUH pengguna kembali melihat klaim seluruh lini. Tidak ada galat yang
-- muncul di layar, dan satu-satunya jejaknya adalah peringatan di log aplikasi:
-- "lini bisnis tidak dapat dibaca; batas data tidak berlaku".
--
-- Itu perilaku yang sengaja dipilih supaya pencabutan tidak mematikan layar — tetapi ia
-- juga berarti pencabutan ini MELONGGARKAN AKSES DATA tanpa terlihat. Jangan
-- menjalankannya tanpa menyadari hal itu.

ALTER TABLE POOLDATA.M_LOGIN_PNC DROP COLUMN LINEBUSINESS;


-- ============================================================================
-- VERIFIKASI
-- ============================================================================
--
-- 1. Kolomnya benar-benar hilang:
--
--      SELECT COUNT(*) AS MASIH_ADA
--        FROM ALL_TAB_COLUMNS
--       WHERE OWNER = 'POOLDATA'
--         AND TABLE_NAME = 'M_LOGIN_PNC'
--         AND COLUMN_NAME = 'LINEBUSINESS';
--
--    Diharapkan: 0.
--
-- 2. Jalur masuk non-karyawan masih berfungsi — tabel ini dipakai provider identitas
--    kedua, dan pencabutan kolom tidak boleh mengganggunya:
--
--      ./claimpnc.exe -periksa
