-- 0008 — Daftar Objek Dokumen: TIDAK ADA YANG PERLU DIJALANKAN
--
-- ============================================================================
-- BERKAS INI SENGAJA TIDAK MEMUAT SATU PUN PERNYATAAN YANG DIJALANKAN.
-- ============================================================================
--
-- Ia dibiarkan ada, bukan dihapus, karena ia merekam PERTANYAAN yang pernah diajukan
-- beserta jawabannya. Menghapusnya akan membuat orang berikutnya mengajukan pertanyaan yang
-- sama dan menebak hal yang sama.
--
--
-- ## Apa yang sempat direncanakan di sini
--
-- Versi pertama berkas ini adalah daftar sembilan pertanyaan untuk DBA, ditambah DDL untuk
-- membuat satu tabel baru dan satu urutan baru. Sebabnya: jalur simpan layar lama —
-- `CNMInsertLstDocObj_act` dan `SetsLstDocObjValue_act` — hilang dari export (`R-16`), dan
-- tidak ada `PEGA_LST_DOC_OBJ.prc` di folder `Database/`. Tiga nama objek karena itu
-- DITEBAK dari pola tabel bersaudaranya.
--
--
-- ## Apa yang ditemukan saat katalog benar-benar dibaca (2026-10-03)
--
-- Seluruh objek yang dibutuhkan SUDAH ADA. Tidak ada DDL yang perlu dijalankan sama sekali.
--
--   POOLDATA.LST_DOC_OBJ         ADA, 12 baris
--                                ID CHAR(6) NOT NULL · OLD_ID CHAR(6) · JSON_DATA CLOB
--                                KET_DOC_OBJ VARCHAR2(20)
--   POOLDATA.LST_DOC_OBJ_SEQ     ADA, LAST_NUMBER 778
--   POOLDATA.V_LST_DOC_OBJ       ADA — `SELECT ID, OLD_ID, KET_DOC_OBJ FROM LST_DOC_OBJ`
--   POOLDATA.V_LST_DOC_OBJ_BISNIS ADA — membongkar `$.LIST_LBU_ID[*].ID` dari JSON_DATA
--   POOLDATA.PEGA_LST_DOC_OBJ    ADA sebagai PROCEDURE, meski hilang dari export
--   POOLDATA.BUSINESS            ADA, 206 baris
--
-- Tiga tebakan yang keliru, dan koreksinya:
--
--   tebakan                         kenyataan
--   ------------------------------- -------------------------------------------------
--   urutan bernama SET_LST_DOC_OBJ  LST_DOC_OBJ_SEQ. SET_LST_DOC_OBJ memang ada, tetapi
--                                   ia PROCEDURE penyusun senarai bisnis
--   nomor urut empat digit          LIMA. ID berbentuk '1' + lpad(seq,5,'0') = CHAR(6),
--                                   terbukti dari 100766..100777 yang terpakai hari ini
--   tabel LST_DOC_OBJ_BUSINESS      ada, tetapi KOSONG dan hanya punya dua kolom
--   dipakai menyimpan pemetaan      (ID_DOC_OBJ, BISNISID). Pemetaan yang sesungguhnya —
--                                   44 baris — ada di dalam JSON_DATA
--
--
-- ## Satu hal yang TIDAK diperbaiki di sini, dan kenapa
--
-- Kolom `KET_DOC_OBJ` KOSONG pada seluruh 12 baris; isinya ada di `JSON_DATA`. Itu sebabnya
-- layar sempat menampilkan 12 baris tanpa nama: view POOLDATA.V_LST_DOC_OBJ hanya membaca
-- kolom.
--
-- Godaannya adalah menambahkan satu UPDATE di sini untuk memindahkan isinya — persis seperti
-- migrasi 0005 pada tabel bersaudaranya. Itu TIDAK dilakukan, dengan tiga alasan:
--
--   1. Tidak perlu. Aplikasi membaca keduanya sekaligus
--      (`COALESCE(KET_DOC_OBJ, JSON_VALUE(JSON_DATA, '$.KET_DOC_OBJ'))`), sehingga nama
--      sudah tampil benar hari ini tanpa satu pun baris disentuh.
--   2. Ia memperbaiki dirinya sendiri. Setiap baris yang disunting lewat layar baru ditulis
--      ke KEDUANYA, sehingga jumlah baris yang hanya punya JSON turun dengan sendirinya.
--   3. UPDATE massal terhadap tabel produksi menuntut persetujuan Work Owner dan pelaksanaan
--      DBA (`D-63`). Meminta ketiganya untuk sesuatu yang tidak mengubah apa pun yang
--      dilihat pengguna bukan pertukaran yang sepadan.
--
-- Bila kelak diputuskan kolom itu harus terisi seluruhnya — misalnya karena ada rule Pega
-- lain yang membaca V_LST_DOC_OBJ dan terganggu oleh NULL — pernyataannya satu baris, dan
-- bentuknya ada di bawah. Ia DIKOMENTARI dengan sengaja.
--
--   -- UPDATE POOLDATA.LST_DOC_OBJ
--   --    SET KET_DOC_OBJ = JSON_VALUE(JSON_DATA, '$.KET_DOC_OBJ')
--   --  WHERE KET_DOC_OBJ IS NULL
--   --    AND JSON_DATA IS NOT NULL;
--   -- COMMIT;
--
-- Verifikasinya, DIHARAPKAN 0:
--
--   -- SELECT COUNT(*) FROM POOLDATA.LST_DOC_OBJ
--   --  WHERE KET_DOC_OBJ IS NULL AND JSON_DATA IS NOT NULL;
--
--
-- ## Hak akses yang dibutuhkan akun aplikasi
--
-- Ini satu-satunya hal yang mungkin masih perlu diminta. Jalankan mode periksa lebih dulu —
-- `claimpnc.exe -periksa` — dan hanya minta yang benar-benar dilaporkan gagal.
--
-- Tanpa DELETE, dan itu bukan kelalaian: `D-66` melarang penghapusan fisik data bernilai
-- bisnis, dan aplikasi memang tidak punya satu pun pernyataan DELETE terhadap objek ini.
--
--   -- GRANT SELECT, INSERT, UPDATE ON POOLDATA.LST_DOC_OBJ      TO <akun aplikasi>;
--   -- GRANT SELECT                 ON POOLDATA.LST_DOC_OBJ_SEQ  TO <akun aplikasi>;
--   -- GRANT SELECT                 ON POOLDATA.BUSINESS         TO <akun aplikasi>;
--   -- GRANT SELECT                 ON POOLDATA.M_SITE_DATABASE  TO <akun aplikasi>;
--
--
-- ## Yang masih layak ditanyakan ke DBA — tidak memblokir apa pun
--
-- 1. POOLDATA.LST_DOC_OBJ_BUSINESS kosong dan tidak dibaca siapa pun, tetapi tiga objek
--    basis data masih bergantung padanya: PEGA_LST_DOC_OBJ, PROCESS_LST_DET_TYPE_DOC, dan
--    PROCESS_LST_DOC_OBJ. Apakah ia peninggalan yang dapat ditinggalkan, atau ada jalur yang
--    belum terlihat yang kelak mengisinya?
--
-- 2. Apakah ada rule atau laporan yang membaca POOLDATA.V_LST_DOC_OBJ dan terganggu oleh
--    KET_DOC_OBJ yang NULL hari ini? Bila ada, UPDATE pada bagian di atas layak dijalankan
--    lebih cepat.
