-- 0008 — Daftar Objek Dokumen: pembatalan
--
-- ============================================================================
-- TIDAK ADA YANG PERLU DIBATALKAN.
-- ============================================================================
--
-- Migrasi naiknya tidak menjalankan satu pun pernyataan: seluruh objek yang dipakai modul
-- Daftar Objek Dokumen SUDAH ADA di basis data sebelum modul ini dibangun. Lihat
-- `0008_daftar_objek_dokumen.up.sql` untuk daftar lengkapnya beserta hasil pembacaan
-- katalog 2026-10-03.
--
--
-- ## Yang TIDAK dapat dibatalkan, dan itu disengaja
--
-- Baris yang sudah disunting lewat layar baru punya `KET_DOC_OBJ` TERISI, sedangkan baris
-- warisan yang belum disentuh masih kosong. Mengosongkannya kembali tidak ada gunanya:
--
--   * Dokumen JSON-nya tetap utuh dan tetap memuat nama yang sama — tidak ada data yang
--     hilang bila kolomnya dikosongkan, dan tidak ada yang kembali bila diisi.
--   * Layar Pega lama membaca JSON lewat POOLDATA.V_LST_DOC_OBJ_BISNIS, bukan kolomnya,
--     sehingga ia tidak terpengaruh sama sekali.
--   * Kolom yang terisi hanya MEMPERBAIKI POOLDATA.V_LST_DOC_OBJ, yang hari ini
--     mengembalikan NULL kepada setiap pembacanya.
--
-- Mengosongkannya kembali karena itu adalah memulihkan keadaan yang lebih buruk tanpa
-- memulihkan apa pun. Pernyataannya tidak disediakan di sini, bahkan sebagai komentar.
--
--
-- ## Bila hak akses perlu dicabut
--
--   -- REVOKE INSERT, UPDATE ON POOLDATA.LST_DOC_OBJ     FROM <akun aplikasi>;
--   -- REVOKE SELECT         ON POOLDATA.LST_DOC_OBJ_SEQ FROM <akun aplikasi>;
--
-- SELECT atas POOLDATA.LST_DOC_OBJ sengaja TIDAK dicabut: layarnya tetap dapat dibuka untuk
-- membaca meski penyimpanannya dimatikan, dan itu keadaan yang lebih berguna daripada layar
-- yang gagal seluruhnya.
--
-- POOLDATA.BUSINESS dan POOLDATA.M_SITE_DATABASE juga tidak dicabut: keduanya dipakai modul
-- lain yang tidak ikut dibatalkan.
