-- 0009 — Daftar Detail Tipe Dokumen (MENU_ID 41)
--
-- ============================================================================
-- PERMINTAAN KE DBA DICABUT. BERKAS INI SENGAJA TIDAK MELAKUKAN APA PUN.
-- ============================================================================
--
-- # Apa yang dulu diminta
--
-- Versi sebelumnya meminta DBA membuat `POOLDATA.LST_DET_TYPE_DOC_BISNIS`, menyalin isi
-- `LST_DET_TYPE_DOC.JSON_DATA` ke dalamnya, lalu mendefinisikan ulang view
-- `V_LST_DET_TYPE_DOC_BISNIS` agar membaca tabel itu. Seluruhnya demi satu hal: grid
-- "Lini Bisnis" pada form modul ini.
--
-- # Kenapa dicabut
--
-- Grid itu tidak ada di layar Pega. Koreksi Work Owner 2026-10-03, dengan tangkapan layar
-- layar "Tambah Data" yang berjalan: isiannya hanya ID Tipe Dokumen dan Detail Dokumen,
-- lalu tombol Simpan.
--
-- Setelah grid dicabut, modul ini tidak lagi menyentuh tabel anak mana pun. Ia membaca
-- `POOLDATA.V_LST_DET_TYPE_DOC` (dijoin ke `V_LST_DOC_TYPE`) dan menulis
-- `POOLDATA.LST_DET_TYPE_DOC` — keduanya SUDAH ADA dan sudah terbukti terbaca: mode
-- periksa melaporkan 159 baris pada 2026-09-23.
--
-- **Tidak ada satu pun objek basis data yang perlu dibuat untuk modul ini.**
--
-- # Yang TIDAK berubah, dan perlu disadari
--
-- Aturan per lini bisnis tetap hidup di dalam `LST_DET_TYPE_DOC.JSON_DATA`, tetap dibaca
-- sembilan rule Pega lewat `V_LST_DET_TYPE_DOC_BISNIS`, dan tetap hanya dapat disunting
-- dari layar Pega selama masa paralel.
--
-- Modul ini **tidak menyentuh kolom JSON_DATA sama sekali** — tidak membaca, tidak
-- menulis, tidak mengosongkan. Karena `detail_update` hanya menyebut sepuluh kolom dan
-- JSON_DATA bukan salah satunya, menyunting sebuah baris dari layar baru TIDAK
-- menghilangkan aturan lini bisnisnya.
--
-- Itu bukan kebetulan melainkan syarat: bila kelak kueri simpan diubah hingga menyentuh
-- JSON_DATA, aturan lini bisnis seluruh baris yang disunting akan hilang — dan hilangnya
-- tidak terlihat di layar mana pun, hanya sebagai dokumen yang berhenti diminta pada
-- klaim.
--
-- # Hak akses yang tetap dibutuhkan
--
-- Bukan DDL, dan mungkin sudah ada. Mode periksa (`claimpnc -periksa`) yang membuktikannya:
--
--   GRANT SELECT               ON POOLDATA.V_LST_DET_TYPE_DOC   TO <akun aplikasi>;
--   GRANT SELECT               ON POOLDATA.V_LST_DOC_TYPE       TO <akun aplikasi>;
--   GRANT SELECT, INSERT, UPDATE ON POOLDATA.LST_DET_TYPE_DOC   TO <akun aplikasi>;
--   GRANT SELECT               ON POOLDATA.M_SITE_DATABASE      TO <akun aplikasi>;
--   GRANT SELECT               ON POOLDATA.LST_DET_TYPE_DOC_SEQ TO <akun aplikasi>;
--
-- Tanpa DELETE: modul ini tidak menghapus apa pun (`D-66`).

SELECT 1 FROM DUAL;
