-- 0011 — Inbox Compliance: penomoran Post Audit (Oracle 19c)
--
-- ============================================================================
-- BACA SELURUH BERKAS INI SEBELUM MENJALANKAN SATU PERNYATAAN PUN.
-- ============================================================================
--
-- Berkas ini TIDAK menyentuh satu pun objek milik sistem lama. Ia hanya membuat SATU
-- sequence baru. Tabel yang memakainya, `POOLDATA.T_CLAIM_COMPLIANCE_H`, sudah ada dan
-- tidak disentuh di sini.
--
-- Meski begitu ia tetap DDL, sehingga tetap menempuh `D-63`: permintaan tertulis tim
-- pengembang, persetujuan Work Owner, pelaksanaan oleh DBA. Akun aplikasi tidak memiliki
-- hak DDL.
--
-- BERKAS INI BELUM PERNAH DIJALANKAN DI LINGKUNGAN MANA PUN.
--
-- Ia harus dijalankan di BASIS DATA SETIAP ENTITAS, bukan hanya di portal utama —
-- `D-75` menetapkan satu basis data per entitas, dan tab Post Audit berlaku di keempatnya.
-- Entitas yang terlewat akan membuat pengiriman ke Post Audit gagal di entitas itu saja,
-- dengan galat yang menyebut sequence tidak ditemukan.
--
-- ============================================================================
-- BENTUK NOMOR BERUBAH — KEPUTUSAN 2026-09-24 DICABUT
-- ============================================================================
--
-- Versi pertama berkas ini membuat `POOLDATA.CPNC_POST_AUDIT_SEQ` yang mulai dari 100001,
-- dan menerbitkan nomor berbentuk `CPL-100001` — meniru bentuk Pega (`CPL-1` … `CPL-19`),
-- dengan pemisahan terbitan lama dan baru dilakukan lewat RENTANG ANGKA.
--
-- Work Owner mencabutnya pada 2026-10-06 dan menetapkan bentuk serta sintaksnya secara
-- harfiah:
--
--     'CPL' || '.' || TO_CHAR(SYSDATE,'RR') || '.'
--            || TO_CHAR(POOLDATA.CLAIM_COMPLIENCE_SEQ.NEXTVAL)
--
-- Hasilnya `CPL.26.1`, sebentuk dengan nomor klaim `PNCN.YY.xxxx` (`D-71`) dan nomor
-- laporan `LPK.YY.xxxx`.
--
-- Ejaan `COMPLIENCE` pada nama sequence SENGAJA dipertahankan apa adanya. Ia ejaan yang
-- Work Owner tulis, dan ia sejalan dengan ejaan yang sudah hidup di sistem lama —
-- access group Pega-nya pun bernama `PncComplience`. Memperbaiki ejaannya di sini akan
-- membuat nama objek basis data berbeda dari yang disebut di permintaan ke DBA.
--
-- # Tiga konsekuensi lama yang IKUT TERCABUT
--
-- Ketiganya tertulis panjang di versi pertama berkas ini, dan ketiganya **tidak lagi
-- berlaku**. Dicatat supaya tidak ada yang mencarinya lalu mengira hilang tanpa sebab.
--
--   1. "Asal nomor tidak terbaca dari bentuknya" — TIDAK LAGI BENAR. `CPL.26.1` dan
--      `CPL-19` berbeda pada karakter keempat: titik versus tanda hubung. Asalnya terbaca
--      langsung, tanpa tabel pemetaan, persis seperti yang `D-22` kehendaki untuk nomor
--      klaim.
--   2. "Rentangnya harus dijaga" — TIDAK LAGI PERLU. Bentuknya sendiri yang memisahkan,
--      sehingga Pega tidak akan pernah menerbitkan nomor yang sama berapa pun angkanya
--      bertambah. Karena itu sequence ini mulai dari 1, bukan 100001.
--   3. "Nomor baru tidak tampil di paling atas" — BERUBAH ARAH. Dalam himpunan karakter
--      Oracle, tanda hubung (`-`) berada SEBELUM titik (`.`), sehingga pada pengurutan
--      teks MENURUN seluruh `CPL.26.x` justru berada DI ATAS seluruh `CPL-nn`. Nomor baru
--      kini tampil paling atas — kebetulan yang menguntungkan, bukan hasil rancangan.
--
-- # Satu masalah lama yang TETAP ADA
--
-- Di dalam bentuk barunya sendiri, urutan teks masih tidak sama dengan urutan penerbitan:
-- `CPL.26.10` berada di atas `CPL.26.9`, karena perbandingan berhenti pada karakter
-- kesembilan (`1` versus `9`).
--
-- Itu akibat langsung `TO_CHAR(...NEXTVAL)` tanpa format mask, yang sintaks Work Owner
-- memang tidak memilikinya. Sintaksnya dipakai APA ADANYA, sama seperti `D-71`
-- memperlakukan sintaks nomor klaim. Bila lebar tetap kelak dikehendaki, yang berubah
-- hanya satu kueri — `post_audit_next_sequence` — menjadi
-- `TO_CHAR(seq.NEXTVAL,'FM0000')`, tanpa menyentuh DDL ini.
--
-- # Tahun diambil dari SYSDATE
--
-- Yakni tanggal server BASIS DATA, bukan tanggal kejadian dan bukan jam aplikasi. Nomor
-- yang terbit di sekitar pergantian tahun mengambil tahunnya dari jam server, dan itu
-- bertaut dengan `R-12`. Konsekuensi yang sama sudah dicatat `D-71` untuk nomor klaim;
-- dicatat ulang di sini supaya tidak perlu dicari ke dokumen lain.
--
-- Catatan teknis: pada `TO_CHAR`, `'RR'` dan `'YY'` menghasilkan dua digit tahun yang
-- IDENTIK. Perbedaan perilaku `RR` hanya berlaku saat MENAFSIRKAN masukan (`TO_DATE`),
-- bukan saat mengeluarkan teks. Sintaks Work Owner dipakai apa adanya.
--
-- NOCACHE dipilih supaya tidak ada nomor yang hilang saat instans dimatikan. Lubang
-- penomoran bukan cacat teknis, tetapi pada nomor yang dibaca orang ia selalu menimbulkan
-- pertanyaan yang mahal dijawab.

CREATE SEQUENCE POOLDATA.CLAIM_COMPLIENCE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Hak pakai untuk akun aplikasi.
--
-- Ganti `APP_CLAIM_PNC` dengan nama akun aplikasi yang sebenarnya di tiap entitas. Tanpa
-- ini, sequence-nya ada tetapi aplikasi tidak dapat memanggilnya — dan galat Oracle
-- berbunyi "sequence does not exist", pesan yang menyesatkan karena objeknya sebenarnya
-- ada dan yang kurang hanyalah haknya.
-- ============================================================================
-- GRANT DI BAWAH SENGAJA DIKOMENTARI — JANGAN DIAKTIFKAN TANPA MEMBACA INI
-- ============================================================================
--
-- Menurut `claim-pnc/backend/.env` baris 60, aplikasi menyambung sebagai
-- POOLDATA_ASM_PENGGUNA=POOLDATA — yakni PEMILIK SKEMA-nya sendiri.
--
-- Dua akibatnya:
--
--   1. GRANT TIDAK DIBUTUHKAN. Pemilik skema selalu punya hak penuh atas objek yang ia
--      miliki; tidak ada hak yang perlu diberikan kepada dirinya sendiri.
--   2. Menjalankannya JUSTRU GAGAL. `APP_CLAIM_PNC` tidak ada di basis data ini, sehingga
--      Oracle melempar `ORA-01917: user or role 'APP_CLAIM_PNC' does not exist` — dan satu
--      pernyataan gagal dapat menghentikan skrip DBA di tengah jalan, meninggalkan
--      sebagian objek terbuat dan sebagian tidak.
--
-- AKTIFKAN baris di bawah HANYA bila aplikasi kelak memakai akun terpisah dari POOLDATA,
-- lalu ganti APP_CLAIM_PNC dengan nama akun itu.
--
-- # Satu pengaman yang TIDAK berlaku selama aplikasi menyambung sebagai POOLDATA
--
-- Ketiadaan `DELETE` pada GRANT dimaksudkan menegakkan `D-66` — soft delete — lewat hak
-- akses basis data, bukan lewat disiplin kode. Pengaman itu **tidak bekerja** pada pemilik
-- skema: POOLDATA dapat menghapus barisnya sendiri apa pun yang tertulis di sini.
--
-- Jadi selama konfigurasi ini berlaku, `D-66` ditegakkan HANYA oleh kode dan oleh review.
-- Itu kelemahan nyata, dan ia hilang begitu akun aplikasi terpisah dibuat.
-- GRANT SELECT ON POOLDATA.CLAIM_COMPLIENCE_SEQ TO APP_CLAIM_PNC;

-- Hak tulis pada tabel tujuannya, yang sudah ada dan tidak dibuat berkas ini.
--
-- Dicatat di sini karena keduanya dibutuhkan bersamaan: tanpa INSERT, pengiriman ke Post
-- Audit tetap gagal meski sequence-nya sudah ada dan dapat dipanggil.
-- GRANT SELECT, INSERT ON POOLDATA.T_CLAIM_COMPLIANCE_H TO APP_CLAIM_PNC;
