-- ============================================================================
-- DICABUT 2026-10-07 — JANGAN DIJALANKAN
-- ============================================================================
--
-- Tabel ini TIDAK JADI DIPAKAI. Work Owner memutuskan Transfer mengikuti Pega apa
-- adanya: PIC Teknik dipindahkan LANGSUNG, tanpa antrean permintaan.
--
-- Dua kenyataan yang mendasarinya:
--
--   1. Antreannya tidak punya pelaksana. Tidak ada satu pun job Pega yang membacanya;
--      kelima job terjadwal (D-57) seluruhnya lebih tua daripada tabel ini. Permintaan
--      akan menumpuk berstatus menunggu, dan pengguna menunggu sesuatu yang tidak
--      akan datang.
--
--   2. P-1 tidak berlaku di jalur ini. Assign per baris di Pega TIDAK memanggil
--      pxTransferAssignment — PNC_ReassignPNCTeknik hanya mengubah ClaimData.UserTeknis.
--      Antrean tugas PC_ASSIGN_WORKLIST tidak disentuh sama sekali.
--
-- Rinciannya di docs/keputusan-implementasi.md §204.
--
-- Yang dibutuhkan sebagai GANTINYA, dan hanya ini:
--
--     GRANT UPDATE (USERTEKNIS_1) ON DATAPEGA.PC_ASM_FW_GCNMFW_WORK TO <akun aplikasi>;
--
-- Berkas ini TIDAK dihapus karena ia rekaman: ia memuat alasan rancangan antrean beserta
-- bentuk tabelnya, dan itu yang dibutuhkan bila kelak jejak audit dituntut kembali.
-- Yang dikembalikan nanti bukan antrean melainkan tabel LOG yang ditulis SESUDAH
-- pemindahan berhasil — bentuknya mirip, artinya berbeda.
--
-- ============================================================================

-- 0014 turun — membatalkan tabel permintaan transfer penugasan.
--
-- ============================================================================
-- MENJALANKAN BERKAS INI MENGHAPUS JEJAK PERMINTAAN
-- ============================================================================
--
-- Isinya SIAPA meminta pekerjaan siapa dipindahkan ke siapa, dan KAPAN. `D-59` menghapus
-- pemisahan tugas, sehingga jejak semacam ini adalah kontrol pengimbang — bukan data
-- pelengkap.
--
-- Pada tabel INI taruhannya khas: permintaan massal memindahkan SELURUH pekerjaan satu
-- operator sekaligus. Jejak yang hilang berarti tidak ada lagi cara mengetahui siapa yang
-- memerintahkan perpindahan itu.
--
-- Jalankan hanya setelah memastikan salah satu dari dua hal:
--
--   1. tabelnya masih KOSONG — migrasi baru saja dijalankan dan tombolnya belum dipakai;
--      atau
--   2. isinya sudah disalin ke tempat yang disetujui Work Owner dan Compliance.
--
-- `P-4` mewajibkan setiap migrasi punya `down` yang benar-benar berfungsi, dan itulah
-- sebabnya berkas ini ada. Ia BUKAN anjuran untuk menjalankannya.
--
-- Ketiga indeks ikut terhapus bersama tabelnya; menghapusnya lebih dulu tidak diperlukan.

DROP TABLE POOLDATA.CPNC_PERMINTAAN_TRANSFER;
