CREATE TABLE POOLDATA.T_OCCUPATIONLIST_ANEKA
(
  IDPEGA                 VARCHAR2(100 BYTE),
  APPLICATIONID          VARCHAR2(100 BYTE),
  NOPOLIS                VARCHAR2(100 BYTE),
  PRODKE                 NUMBER(38),
  INDEXOBJECTLOCATION    NUMBER(38),
  INDEXOBJECTOCCUPATION  NUMBER(38),
  OCCUPATIONID           VARCHAR2(100 BYTE),
  OCCUPATIONNAME         VARCHAR2(500 BYTE),
  SUBOCCUPATIONID        VARCHAR2(100 BYTE),
  SUBOCCUPATIONNAME      VARCHAR2(500 BYTE),
  FLAGOLDDATA            VARCHAR2(10 BYTE),
  FLAGEDITDATA           VARCHAR2(10 BYTE),
  FLAGDELETE             VARCHAR2(10 BYTE)
)