CREATE TABLE POOLDATA.M_LOGIN_GROUP_PNC
( LOGIN_ID VARCHAR2(50),
  GROUP_ID VARCHAR2(100),
  CONSTRAINT M_LOGIN_GROUP_PNC_PK PRIMARY KEY (LOGIN_ID, GROUP_ID) 
)
/ 

CREATE TABLE POOLDATA.M_APLIKASI
(
  APP_ID        NUMBER(3) NOT NULL,
  APP_DESC      VARCHAR2(60 BYTE),
  STS_AKTIF     CHAR(1 BYTE),
  LAST_VERSION  VARCHAR2(20 BYTE),
  CONSTRAINT PK_M_APLIKASI PRIMARY KEY (APP_ID)  
)
/

CREATE TABLE POOLDATA.M_MENU_APLIKASI_PNC
(
  APP_ID          NUMBER(3)  NOT NULL,
  MENU_ID         NUMBER(5)  NOT NULL,
  MENU_DESC       VARCHAR2(100 BYTE),
  MENU_PROGRAM    VARCHAR2(100 BYTE),
  APP_ID_LEADER   NUMBER(3),
  MENU_ID_LEADER  NUMBER(5),
  MENU_SEQUENCE   NUMBER(6),
  CONSTRAINT PK_M_MENU_APLIKASI_PNC PRIMARY KEY (APP_ID, MENU_ID)
)
/

CREATE INDEX POOLDATA.M_MENU_APLIKASI_PNC_IDX01 ON POOLDATA.M_MENU_APLIKASI_PNC
(APP_ID, MENU_ID_LEADER)
/

CREATE UNIQUE INDEX POOLDATA.M_MENU_APLIKASI_PNC_IDX2 ON POOLDATA.M_MENU_APLIKASI_PNC
(APP_ID, MENU_ID, LOWER(TRIM(MENU_DESC)))
/

CREATE INDEX POOLDATA.M_MENU_APLIKASI_PNC_IDX3 ON POOLDATA.M_MENU_APLIKASI_PNC
(APP_ID, MENU_ID, MENU_ID_LEADER)
/

ALTER TABLE POOLDATA.M_MENU_APLIKASI_PNC 
ADD CONSTRAINT FK_M_MENU_APL_REF_M_APLIKASI FOREIGN KEY (APP_ID) REFERENCES POOLDATA.M_APLIKASI (APP_ID)
/

CREATE TABLE POOLDATA.M_OTORISASI_PNC
(
  LOGIN_ID_GROUP VARCHAR2(100) NOT NULL,
  APP_ID   NUMBER(3) NOT NULL,
  MENU_ID  NUMBER(5) NOT NULL,
  CONSTRAINT PK_M_OTORISASI_PNC PRIMARY KEY (LOGIN_ID_GROUP, APP_ID, MENU_ID)
)
/

ALTER TABLE POOLDATA.M_OTORISASI_PNC 
ADD CONSTRAINT FK_M_OTORIS_REF_M_MENU_APL FOREIGN KEY (APP_ID, MENU_ID) REFERENCES POOLDATA.M_MENU_APLIKASI_PNC (APP_ID,MENU_ID)
/