CREATE TABLE POOLDATA.TMP_BATCH_AUTO_CLAIM
(
  BATCH           NUMBER,
  INISIALID       VARCHAR2(20 BYTE),
  NOPOLIS         VARCHAR2(30 BYTE),
  PRODKE          VARCHAR2(15 BYTE),
  TGLPROSES       TIMESTAMP(6),
  USERINPUT       VARCHAR2(50 BYTE),
  IDPEGA          VARCHAR2(100 BYTE),
  TGLKEJADIAN     VARCHAR2(50 BYTE),
  TGLLAPOR        VARCHAR2(50 BYTE),
  CURRENCY        VARCHAR2(15 BYTE),
  COL_ID          VARCHAR2(20 BYTE),
  NILAIKLAIM      NUMBER,
  NOTE            VARCHAR2(300 BYTE),
  KEYWORD         VARCHAR2(100 BYTE),
  TMP_MESSAGE     VARCHAR2(100 BYTE),
  NOAKSEPTASI     VARCHAR2(50 BYTE),
  PROGRESS        VARCHAR2(50 BYTE),
  OBJECTNAME      VARCHAR2(100 BYTE),
  FLAGTIDAKBAYAR  VARCHAR2(50 BYTE),
  CONSTRAINT TMP_BATCH_AUTO_CLAIM_PK PRIMARY KEY (NOPOLIS, TGLPROSES, TGLKEJADIAN)
)
/

CREATE INDEX POOLDATA.TMP_BATCH_AUTO_CLAIM_IDX ON POOLDATA.TMP_BATCH_AUTO_CLAIM
(BATCH, INISIALID, NOPOLIS, PRODKE, TGLKEJADIAN, 
TMP_MESSAGE, IDPEGA)
/

CREATE TABLE POOLDATA.M_AUTO_CLAIM_PNC
(
  INISIALID        VARCHAR2(15 BYTE)            NOT NULL,
  NAMA_PENERIMA    VARCHAR2(40 BYTE),
  BANK_PENERIMA    VARCHAR2(40 BYTE),
  NO_REKENING      VARCHAR2(20 BYTE),
  PCT_MAX          NUMBER,
  PIC_LAPOR        VARCHAR2(50 BYTE),
  EMAIL_LAPOR      VARCHAR2(500 BYTE),
  CLAIM_ALLOWED    NUMBER,
  ALAMAT_PENERIMA  VARCHAR2(200 BYTE),
  USERINPUT        VARCHAR2(100 BYTE),
  KOMITE           VARCHAR2(100 BYTE),
  APPROVAL         VARCHAR2(5 BYTE),
  CLIENTID         VARCHAR2(100 BYTE),
  CLIENTNAME       VARCHAR2(100 BYTE),
  CONSTRAINT M_AUTO_CLAIM_PNC_PK PRIMARY KEY (INISIALID)
)
/