CREATE OR REPLACE PROCEDURE GENERAL.GET_TOKEN_STORAGE(
   VAPPNAME IN VARCHAR,
   VUSERINPUT IN VARCHAR,
   VAKSESTOKEN OUT VARCHAR2,
   VERRMSG OUT VARCHAR2
) 
as
begin
    
    BEGIN
        select standard_hash('ASMAPP'||SYSTIMESTAMP,'MD5') into VAKSESTOKEN from dual;
        
        INSERT INTO GENERAL.GCP_IMAGE(APPNAME,KODEAKSES,USERINPUT,INPUTDATE) values (VAPPNAME, VAKSESTOKEN, VUSERINPUT, sysdate);
        COMMIT;
        
    END;
    
exception when OTHERS then
    VAKSESTOKEN := null;
    VERRMSG := SQLERRM;
    return;
end GET_TOKEN_STORAGE;
/
