CREATE OR REPLACE PROCEDURE          InsertDataAIKlaimPNC(
flags in varchar2,
tCLAIMID in varchar2,
tOBJECTID in varchar2,
tCOVERAGEID in varchar2,
tADJUSTMENTID in varchar2,
tOBJECTNAME in varchar2,
tRESULTAI in varchar2,
tKOMITE in varchar2,
tPENGGUNAAN_WORDING_POLIS in varchar2,
tSTS_FINAL in varchar2,
tCONF_SCORE in number,
tKATEGORI_KRONOLOGI in varchar2,
tCOVERAGE_AI_FINAL in varchar2,
tCAUSE_OF_LOSS in varchar2,
tBATASLAPOR in varchar2,
tBATASUMUR in varchar2,
tCOVERAGEKRONOLOGI in varchar2,
tKELENGKAPANDOKUMEN in varchar2,
tPERIODEPOLIS in varchar2,
tNOTETERIMA in varchar2,
tNOTETOLAK in varchar2,
tKOMITESTATUS in varchar2,
tNOTEKOMITE in varchar2, TTGLKOMITE in DATE,
tCoverageTerima in varchar2,
tCoverageTolak in varchar2,
tCoverageNoteTerima in varchar2,
tCoverageNoteTolak in varchar2,
tCoveragejson in clob,
ErrMsg OUT VARCHAR2)
as
counts_id number;
t_TTGLKOMITE Date;

BEGIN
   
   select count(*) into counts_id from POOLDATA.T_CLAIM_DATA_RESULTS_AI where CLAIMID=tCLAIMID and OBJECTID=tOBJECTID and COVERAGEID=tCOVERAGEID and OBJECTNAME=tOBJECTNAME;
   
   if counts_id=0 and flags!='update' and flags!='komite' and flags!='new' then 
   
        INSERT INTO POOLDATA.T_CLAIM_DATA_RESULTS_AI(CLAIMID,OBJECTID,COVERAGEID,ADJUSTMENTID,OBJECTNAME,RESULTAI,KOMITE,PENGGUNAAN_WORDING_POLIS,STS_FINAL,CONF_SCORE,KATEGORI_KRONOLOGI,COVERAGE_AI_FINAL,CAUSE_OF_LOSS,
        BATASLAPOR,BATASUMUR,COVERAGEKRONOLOGI,KELENGKAPANDOKUMEN,PERIODEPOLIS,NOTETERIMA,NOTETOLAK,TGLAI,COVERAGE_TERIMA,COVERAGE_TOLAK,NOTE_COVERAGE_TERIMA,NOTE_COVERAGE_TOLAK)
        VALUES(tCLAIMID,tOBJECTID,tCOVERAGEID,tADJUSTMENTID,tOBJECTNAME,tRESULTAI,tKOMITE,tPENGGUNAAN_WORDING_POLIS,tSTS_FINAL,tCONF_SCORE,tKATEGORI_KRONOLOGI,tCOVERAGE_AI_FINAL,tCAUSE_OF_LOSS,
        tBATASLAPOR,tBATASUMUR,tCOVERAGEKRONOLOGI,tKELENGKAPANDOKUMEN,tPERIODEPOLIS,tNOTETERIMA,tNOTETOLAK,sysdate,tCoverageTerima,tCoverageTolak,tCoverageNoteTerima,tCoverageNoteTolak);
        ErrMsg:='Sukses Insert Data';
        COMMIT;
   elsif flags='update' then
        select count(*) into counts_id from POOLDATA.T_CLAIM_DATA_RESULTS_AI 
        where KOMITE=tKOMITE;
        t_TTGLKOMITE :=TTGLKOMITE;
        ErrMsg:='Sukses Update Data';
   elsif flags='komite' then
        select count(*) into counts_id from POOLDATA.T_CLAIM_DATA_RESULTS_AI 
        where CLAIMID=tCLAIMID and OBJECTID=tOBJECTID and COVERAGEID=tCOVERAGEID;
        
        if counts_id>0 then
            update POOLDATA.T_CLAIM_DATA_RESULTS_AI a set KOMITE=tKOMITE
            where CLAIMID=tCLAIMID and OBJECTID=tOBJECTID and COVERAGEID=tCOVERAGEID;
            ErrMsg:='Sukses Update Data';
            COMMIT;
        end if;
   elsif flags='new' then
        select count(*) into counts_id from POOLDATA.T_CLAIM_DATA_RESULTS_AI 
        where CLAIMID=tCLAIMID and OBJECTID=tOBJECTID and COVERAGEID=tCOVERAGEID;
        
        if counts_id=0 then
            INSERT INTO POOLDATA.T_CLAIM_DATA_RESULTS_AI(CLAIMID,OBJECTID,COVERAGEID,ADJUSTMENTID,OBJECTNAME,RESULTAI,KOMITE,PENGGUNAAN_WORDING_POLIS,STS_FINAL,CONF_SCORE,KATEGORI_KRONOLOGI,COVERAGE_AI_FINAL,CAUSE_OF_LOSS,
        BATASLAPOR,BATASUMUR,COVERAGEKRONOLOGI,KELENGKAPANDOKUMEN,PERIODEPOLIS,NOTETERIMA,NOTETOLAK,TGLAI,COVERAGE_TERIMA,COVERAGE_TOLAK,NOTE_COVERAGE_TERIMA,NOTE_COVERAGE_TOLAK)
            Select CLAIMID,OBJECTID,case when COVERAGEID!= tCOVERAGEID then tCOVERAGEID else '' end,ADJUSTMENTID,OBJECTNAME,
            case when RESULTAI!= tRESULTAI then tRESULTAI else RESULTAI end
            ,case when KOMITE!= tKOMITE then tKOMITE else KOMITE end,PENGGUNAAN_WORDING_POLIS,STS_FINAL,CONF_SCORE,KATEGORI_KRONOLOGI,COVERAGE_AI_FINAL,CAUSE_OF_LOSS,
        BATASLAPOR,BATASUMUR,COVERAGEKRONOLOGI,KELENGKAPANDOKUMEN,PERIODEPOLIS,NOTETERIMA,NOTETOLAK,TGLAI,COVERAGE_TERIMA,COVERAGE_TOLAK,NOTE_COVERAGE_TERIMA,NOTE_COVERAGE_TOLAK
          from POOLDATA.T_CLAIM_DATA_RESULTS_AI where CLAIMID=tCLAIMID and OBJECTID=tOBJECTID and OBJECTNAME=tOBJECTNAME;
            ErrMsg:='Sukses Update Data';
            COMMIT;
        end if;
   end if;
   
   
   
   EXCEPTION
      WHEN OTHERS
      THEN
         ErrMsg := 'Insert Data Results AI ';
         RETURN;
   END;

/