-- Kolom yang DIPAKAI kueri modul Dashboard Claim tetapi TIDAK ADA di tabelnya.
-- Hasil KOSONG = seluruh kolom ada, dan penyebab galat 500 bukan nama kolom.
SELECT D.NAMA AS KOLOM_HILANG
  FROM (
          SELECT 'ADJUSTERPIC_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'ADJUSTERSTATUS_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'BRANCHNAME' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'BUSINESSCODE_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'BUSINESSNAME' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'CASEID_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'DATEOFLOSS_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'GROUPPANEL_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'POLICYNO' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PXASSIGNEDOPERATORID' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PXCREATEDATETIME' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PXCREATEOPNAME' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PXFLOWNAME' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PXOBJCLASS' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PXTASKLABEL' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PYID' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PYSTATUSWORK' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'PZINSKEY' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'QQNAME' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'REFNO_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'REPORTDATE_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'RESCHEDULEDATE_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'RESCHEDULELOCATION_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'SOBNAME' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'STATUSCLAIM_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'SURVEYORNAME_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'SURVEYORTYPE_1' AS NAMA FROM DUAL
 UNION ALL
          SELECT 'USERTEKNIS_1' AS NAMA FROM DUAL
       ) D
 WHERE NOT EXISTS (SELECT 1
                     FROM ALL_TAB_COLUMNS T
                    WHERE T.OWNER       = 'POOLDATA'
                      AND T.TABLE_NAME  = 'T_CLAIMLIST_ADMIN'
                      AND T.COLUMN_NAME = D.NAMA)
 ORDER BY 1;
