package reportklaim

// Tabel kolom berkas CSV untuk laporan kelompok Klaim.
//
// Judul kolom disalin APA ADANYA dari export, termasuk salah ketik dan spasi
// gandanya — lihat Column.Header pada report.go untuk alasannya.

// colsTATPersonal — 52 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCTATReport1_Act-Act.xml`.
var colsTATPersonal = []Column{
	{Header: "No Klaim", Field: "CaseID"},
	{Header: "RCV", Field: "RefNo"},
	{Header: "No polis", Field: "ClaimNo"},
	{Header: "Nama tertanggung", Field: "LossCoverage"},
	{Header: "Sumber bisnis", Field: "DollarCurrencyVal"},
	{Header: "Coverage", Field: "UserTeknisGroup"},
	{Header: "Status Klaim", Field: "AnalystDoctorRemaks"},
	{Header: "Posisi", Field: "TelpTertanggung"},
	{Header: "No Akseptasi", Field: "IsAnalisTransfer"},
	{Header: "Jumlah yang diakseptasi", Field: "FlagReject"},
	{Header: "Tgl receive dokumen", Field: "CommentKomiteClosecase"},
	{Header: "tgl masuk analis", Field: "KirimAnalystDate"},
	{Header: "tgl analis-invest", Field: "KirimInvestDate"},
	{Header: "Tgl registrasi", Field: "City"},
	{Header: "Tgl tf invest - analyst", Field: "IdxSurveyResults"},
	{Header: "Tgl tf analyst - PUCL/RCL", Field: "ClaimEstimate"},
	{Header: "Tgl tf RCL/PUCL-Analyst", Field: "AlasanTerlambat"},
	{Header: "RCL/PUCL/Notifikasi", Field: "ExGratia"},
	{Header: "Tgl tf analyst - compliance", Field: "Province"},
	{Header: "tgl tf complicance-analyst", Field: "IsCFS_PNC"},
	{Header: "Tgl bayar CPL", Field: "CompliancePosAuditByr"},
	{Header: "Tgl postAudit CPL", Field: "IsBackCFS"},
	{Header: "Tgl bayar CPL postAuditIs", Field: "IsTransferPIC"},
	{Header: "TransferPIC", Field: "Location"},
	{Header: "Tgl tf analyst - komite", Field: "AnaylstRemarks"},
	{Header: "invest 1/0", Field: "IsInvest"},
	{Header: "compliance 1/0", Field: "isCompliance"},
	{Header: "Tgl komite akseptasi", Field: "StatusWork"},
	{Header: "Tgl krm propose adjustment", Field: "CountryID"},
	{Header: "Tgl akseptasi", Field: "ComplianceRemark"},
	{Header: "Tgl Bayar", Field: "UserBusinessPA"},
	{Header: "Tipe Pembayaran", Field: "ReporterName"},
	{Header: "Status bayar", Field: "DistrictID"},
	{Header: "Tgl tutup klaim", Field: "ExGratiaNote"},
	{Header: "Alasan keterlambatan", Field: "Remark"},
	{Header: "Inputor", Field: "pyLabel"},
	{Header: "Tgl Cetak LOD", Field: "ResponseNote"},
	{Header: "Tgl Trf Investigator", Field: "DateKomite"},
	{Header: "Tgl Terima LOD", Field: "ResponseNote"},
	{Header: "Tgl Transfer Kasir", Field: "pyEmailAddress"},
	{Header: "Report Date", Field: "CASEDB"},
	{Header: "Start Date Polis", Field: "ClaimNoSRB"},
	{Header: "End Date Polis", Field: "NoPla"},
	{Header: "Date Of Accident", Field: "DaftarObjek"},
	{Header: "Remark", Field: "Status"},
	{Header: "Tgl Analis To Inputor", Field: "HideKTP"},
	{Header: "Risk Location", Field: "RiskLocation"},
	{Header: "DOB", Field: "DOB"},
	{Header: "Usia pada saat klaim", Field: "USIA"},
	{Header: "Diagnosa", Field: "Diagnose"},
	{Header: "Nature Of Loss", Field: "NatureOfLoss"},
	{Header: "Perhitungan jarak antara terbit polis - tanggal kejadian", Field: "PolicyRange"},
}

// colsTATNonMBU — 39 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCTATReport1_Act-Act.xml`.
var colsTATNonMBU = []Column{
	{Header: "No Klaim", Field: "CaseID"},
	{Header: "No Polis", Field: "ClaimNo"},
	{Header: "Nama tertanggung", Field: "LossCoverage"},
	{Header: "Nama bisnis", Field: "AlasanDokterRejectRCL"},
	{Header: "Sumber bisnis", Field: "DollarCurrencyVal"},
	{Header: "Klaim Leader/Member", Field: "NamaDokterRCL"},
	{Header: "Nomor Akseptasi", Field: "IsAnalisTransfer"},
	{Header: "Tahun Of Loss", Field: "CauseOfLoss"},
	{Header: "Tgl kejadian", Field: "DaftarObjek"},
	{Header: "Tgl terima dokumen", Field: "CommentKomiteClosecase"},
	{Header: "Tgl Registrasi", Field: "City"},
	{Header: "Tgl selesai registrasi", Field: "Location"},
	{Header: "Tgl tf PLA", Field: "InsuredRelationshipOthers"},
	{Header: "Lama proses regis-tf ke teknik", Field: "CloseClaimNote"},
	{Header: "Tgl permintaan kelengkapan dokumen", Field: "isComplianceTransfer"},
	{Header: "Tgl Survey", Field: "UserAdmin"},
	{Header: "Tgl aksep komite", Field: "AnaylstRemarks"},
	{Header: "Tgl Selesai Cek Komite", Field: "LokasiSurveyor"},
	{Header: "Tgl krm propose adjustment", Field: "CountryID"},
	{Header: "Tgl Terima LOD", Field: "ResponseNote"},
	{Header: "Tgl Akseptasi", Field: "ComplianceRemark"},
	{Header: "Tgl akseptasi manual", Field: "IsTransferAnalisator"},
	{Header: "Tgl DLA", Field: "RCV_ID"},
	{Header: "Tgl bayar", Field: "UserBusinessPA"},
	{Header: "Status Bayar", Field: "DistrictID"},
	{Header: "Lama regis - tanggal trf kasir", Field: "CityID"},
	{Header: "Lama aksep - trf kasir", Field: "OccupationCode"},
	{Header: "Lama akseptasi - tanggal bayar", Field: "Conveyance"},
	{Header: "Status klaim", Field: "AnalystDoctorRemaks"},
	{Header: "PIC Teknik", Field: "NoKTP"},
	{Header: "Tgl tutup kaim", Field: "ExGratiaNote"},
	{Header: "ctt tutup kaim", Field: "NIK"},
	{Header: "Alasan keterlambatan", Field: "Remark"},
	{Header: "Tgl Trf PIC", Field: "NewNoKTP"},
	{Header: "PIC Admin", Field: "pyLabel"},
	{Header: "Tgl Dok Lengkap", Field: "pyGroup"},
	{Header: "Tgl Trf Komite", Field: "pyCountryName"},
	{Header: "Tgl Trf Kasir", Field: "NewEmail"},
	{Header: "Report Date", Field: "CASEDB"},
}

// colsTATBonding — 34 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCTATReport1_Act-Act.xml`.
var colsTATBonding = []Column{
	{Header: "No Klaim", Field: "CaseID"},
	{Header: "No Polis", Field: "ClaimNo"},
	{Header: "Nama tertanggung", Field: "LossCoverage"},
	{Header: "Nama bisnis", Field: "AlasanDokterRejectRCL"},
	{Header: "Sumber bisnis", Field: "DollarCurrencyVal"},
	{Header: "Klaim Leader/Member", Field: "NamaDokterRCL"},
	{Header: "Nomor Akseptasi", Field: "IsAnalisTransfer"},
	{Header: "Tahun Of Loss", Field: "CauseOfLoss"},
	{Header: "Tgl kejadian", Field: "DaftarObjek"},
	{Header: "Tgl terima dokumen", Field: "CommentKomiteClosecase"},
	{Header: "Tgl Registrasi", Field: "City"},
	{Header: "Tgl selesai registrasi", Field: "AnalystRemaksInvestigator"},
	{Header: "Tgl tf ke PIC Teknik", Field: "Location"},
	{Header: "Tgl tf PLA", Field: "InsuredRelationshipOthers"},
	{Header: "Lama proses regis-tf ke teknik", Field: "CloseClaimNote"},
	{Header: "Tgl permintaan kelengkapan dokumen", Field: "isComplianceTransfer"},
	{Header: "Tgl Survey", Field: "UserAdmin"},
	{Header: "Tgl aksep komite", Field: "AnaylstRemarks"},
	{Header: "Tgl Selesai Cek Komite", Field: "LokasiSurveyor"},
	{Header: "Tgl krm propose adjustment", Field: "CountryID"},
	{Header: "Tgl Terima LOD", Field: "ResponseNote"},
	{Header: "Tgl Akseptasi", Field: "ComplianceRemark"},
	{Header: "Tgl akseptasi manual", Field: "IsTransferAnalisator"},
	{Header: "Tgl DLA", Field: "RCV_ID"},
	{Header: "Tgl bayar", Field: "UserBusinessPA"},
	{Header: "Status Bayar", Field: "DistrictID"},
	{Header: "Lama regis - request bayar", Field: "CityID"},
	{Header: "Lama akseptasi - request bayar", Field: "Conveyance"},
	{Header: "Status klaim", Field: "AnalystDoctorRemaks"},
	{Header: "PIC Teknik", Field: "NoKTP"},
	{Header: "Tgl tutup kaim", Field: "ExGratiaNote"},
	{Header: "ctt tutup kaim", Field: "NIK"},
	{Header: "Alasan keterlambatan", Field: "Remark"},
	{Header: "Report Date", Field: "CASEDB"},
}

// colsKlaimHarianRingkas — 10 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCReportHarian_act1-Act.xml`.
var colsKlaimHarianRingkas = []Column{
	{Header: "Tanggal regist", Field: "City"},
	{Header: "No Polis", Field: "AlasanDokterRejectRCL"},
	{Header: "Atas Nama tertanggung", Field: "AlasanTerlambat"},
	{Header: "No Klaim", Field: "AnalystDoctorRemaks"},
	{Header: "DOL", Field: "AnaylstRemarks"},
	{Header: "Tanggal Transfer PIC", Field: "District"},
	{Header: "Tanggal Terima Dokumen", Field: "DistrictID"},
	{Header: "Nilai Klaim(100%)", Field: "CloseClaimNote"},
	{Header: "Nilai Klaim(Share ASM)", Field: "ComplianceRemark"},
	{Header: "PIC Teknik", Field: "ExGratiaNote"},
}

// colsKlaimHarian — 30 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCReportHarian_act1-Act.xml`.
var colsKlaimHarian = []Column{
	{Header: "No Polis", Field: "NoKTP"},
	{Header: "PNC CaseID", Field: "CaseID"},
	{Header: "Nama Tertanggung", Field: "NamaSurveyor"},
	{Header: "COB", Field: "City"},
	{Header: "PIC Teknik", Field: "UserAdmin"},
	{Header: "Email", Field: "AnalystTransferDate"},
	{Header: "Tgl Regis", Field: "Email"},
	{Header: "Bulan Klaim", Field: "DateOfLoss"},
	{Header: "Date of Loss", Field: "CityID"},
	{Header: "SOB", Field: "AgingAmount"},
	{Header: "Leader/ Member/Fac In", Field: "Country"},
	{Header: "Nature of Loss", Field: "Country"},
	{Header: "Cause of Loss", Field: "AlasanTerlambat"},
	{Header: "ASM Share", Field: "CloseClaimNote"},
	{Header: "Deductible", Field: "CommentKomiteClosecase"},
	{Header: "Nilai Share ASM", Field: "ComplianceRemark"},
	{Header: "Nilai Klaim 100%", Field: "Conveyance"},
	{Header: "Adjuster fee 100 % Share", Field: "UserName"},
	{Header: "Nilai Klaim Net 100 %", Field: "UserTeknis"},
	{Header: "Nilai Klaim Net ASM Share", Field: "CompliancePosAuditByr"},
	{Header: "Lack of Doc/Salvage/Recovery/Subrogaration", Field: "AnalystRemaksInvestigator"},
	{Header: "Cabang", Field: "ClaimNo"},
	{Header: "Status", Field: "LokasiSurveyor"},
	{Header: "Kronologis", Field: "NIK"},
	{Header: "Tgl terima dokumen", Field: "NPWP"},
	{Header: "Tgl tf ke PIC Teknik", Field: "TransferPICDate"},
	{Header: "Remark", Field: "AnaylstRemarks"},
	{Header: "PIC Admin Regist", Field: "NewEmail"},
	{Header: "Location", Field: "Location"},
	{Header: "No Reff Broker", Field: "NoReffBroker"},
}

// colsRejectKlaim — 33 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCReportDataReject_act-Act.xml`.
var colsRejectKlaim = []Column{
	{Header: "No Klaim", Field: "CaseID"},
	{Header: "Nopolis", Field: "NoKTP"},
	{Header: "QQName", Field: "ClaimID"},
	{Header: "Nama Bisnis", Field: "ClaimNo"},
	{Header: "PIC Teknik", Field: "Conveyance"},
	{Header: "Tgl Registrasi", Field: "Country"},
	{Header: "Tgl Kejadian", Field: "CountryID"},
	{Header: "Tgl Reject", Field: "Email"},
	{Header: "Bulan Reject", Field: "FlagASO"},
	{Header: "Alasan Reject", Field: "CityID"},
	{Header: "Estimasi Value", Field: "Resources"},
	{Header: "Share ASM", Field: "ClaimAmount"},
	{Header: "Persen OR", Field: "OwnRisk"},
	{Header: "Reject Note", Field: "CloseClaimNote"},
	{Header: "Coins", Field: "FlagReject"},
	{Header: "PSRSPL", Field: "InsuredRelationship"},
	{Header: "QS_RI", Field: "PolicyObjectLocationRWNote"},
	{Header: "ER1", Field: "IsBackCFS"},
	{Header: "ER2", Field: "IsCFS"},
	{Header: "SURPLUS1", Field: "isComplianceTransfer"},
	{Header: "SURPLUS2", Field: "IsTransferAnalisator"},
	{Header: "PSRQS_RI", Field: "IsTransferPIC"},
	{Header: "PSRQS_OR", Field: "InsuredRelationshipOthers"},
	{Header: "ORS", Field: "KomiteStatus"},
	{Header: "Facultative", Field: "District"},
	{Header: "Facobl", Field: "LokasiSurveyor"},
	{Header: "BPPDAN", Field: "LossCoverage"},
	{Header: "XL", Field: "NamaDokumen"},
	{Header: "PSS", Field: "NamaSurveyor"},
	{Header: "PRGBI", Field: "NIK"},
	{Header: "FESPL", Field: "AnalystRemaksInvestigator"},
	{Header: "PFRA", Field: "ProdKe"},
	{Header: "Fac_Out", Field: "AlasanDokterRejectRCL"},
}

// colsCloseKlaimRingkas — 11 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCReportDataClose_act-Act.xml`.
var colsCloseKlaimRingkas = []Column{
	{Header: "No Klaim", Field: "CaseID"},
	{Header: "Nopolis", Field: "NoKTP"},
	{Header: "QQName", Field: "ClaimID"},
	{Header: "Nama Bisnis", Field: "ClaimNo"},
	{Header: "PIC Teknik", Field: "Conveyance"},
	{Header: "Tgl Registrasi", Field: "Country"},
	{Header: "Tgl Kejadian", Field: "CountryID"},
	{Header: "Tgl Akseptasi", Field: "District"},
	{Header: "No Akseptasi", Field: "DistrictID"},
	{Header: "Tgl Close", Field: "Email"},
	{Header: "Bulan Close", Field: "FlagASO"},
}

// colsCloseKlaim — 81 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/PNCReportDataClose_act-Act.xml`.
var colsCloseKlaim = []Column{
	{Header: "No Klaim", Field: "CaseID"},
	{Header: "Bisnis", Field: "KodeCabang"},
	{Header: "Remark PIC", Field: "AlasanDokterRejectRCL"},
	{Header: "No Polis", Field: "TKI"},
	{Header: "Client Name", Field: "AnalystDoctorRemaks"},
	{Header: "Nama Mo", Field: "AnalystRemaksInvestigator"},
	{Header: "Okupasi", Field: "AnaylstRemarks"},
	{Header: "No Aksep", Field: "City"},
	{Header: "Cause Of Loss", Field: "CauseOfLoss"},
	{Header: "Coverage Name", Field: "CityID"},
	{Header: "Sts Exgratia", Field: "ClaimEstimate"},
	{Header: "Date Of Loss", Field: "StatusWork"},
	{Header: "Month DOL", Field: "ClaimNo"},
	{Header: "Year DOL", Field: "CloseClaimNote"},
	{Header: "Prepare Date", Field: "UserTeknisEmail"},
	{Header: "Thn Regis", Field: "CommentKomiteClosecase"},
	{Header: "THN POLIS", Field: "RefNo"},
	{Header: "Tgl Aksep", Field: "DollarCurrencyVal"},
	{Header: "Month Aksep", Field: "CompliancePosAuditByr"},
	{Header: "Year Aksep", Field: "ComplianceRemark"},
	{Header: "Tgl Reject", Field: "UserTeknis"},
	{Header: "Month Reject", Field: "Conveyance"},
	{Header: "Thn Reject", Field: "Country"},
	{Header: "Begin Date", Field: "UserTeknisGroup"},
	{Header: "End Date", Field: "RemarkRecommendation"},
	{Header: "TAT", Field: "UserName"},
	{Header: "TSI", Field: "ProvinceID"},
	{Header: "Total Aksep", Field: "CountryID"},
	{Header: "Below 100jt", Field: "DokumenLengkap"},
	{Header: "Total OS", Field: "Currency"},
	{Header: "Reject Klaim", Field: "Province"},
	{Header: "LEADER/MEMBER/FACIN", Field: "DaftarObjek"},
	{Header: "Risk Loc", Field: "Location"},
	{Header: "Risk Loc Klaim", Field: "pyID"},
	{Header: "PIC Klaim", Field: "DistrictID"},
	{Header: "Own Retension", Field: "ExGratiaNote"},
	{Header: "Coins", Field: "FlagReject"},
	{Header: "PSRSPL", Field: "InsuredRelationship"},
	{Header: "QS_RI", Field: "Investigasi"},
	{Header: "ER1", Field: "IsBackCFS"},
	{Header: "ER2", Field: "IsCFS_PNC"},
	{Header: "SURPLUS1", Field: "isComplianceTransfer"},
	{Header: "SURPLUS2", Field: "IsTransferAnalisator"},
	{Header: "PSRQS_RI", Field: "IsTransferPIC"},
	{Header: "PSRQS_OR", Field: "InsuredRelationshipOthers"},
	{Header: "ORS", Field: "KomiteStatus"},
	{Header: "Facultative", Field: "District"},
	{Header: "Facobl", Field: "LokasiSurveyor"},
	{Header: "BPPDAN", Field: "LossCoverage"},
	{Header: "XL", Field: "NamaDokumen"},
	{Header: "PSS", Field: "NamaSurveyor"},
	{Header: "PRGBI", Field: "NIK"},
	{Header: "FESPL", Field: "NoKTP"},
	{Header: "PFRA", Field: "ProdKe"},
	{Header: "Nilai Klaim yang Diajukan Tertanggung", Field: "Password"},
	{Header: "Adjustment Klaim (Self Adjustment)", Field: "RCV_ID"},
	{Header: "Adjustment Klaim (Adjuster)", Field: "ReportAddress"},
	{Header: "Selisih Estimasi Klaim dengan Adjustment", Field: "Remark"},
	{Header: "Adjuster Fee", Field: "ReporterName"},
	{Header: "Nilai Klaim yang Diajukan Tertanggung OR", Field: "ReportDescription"},
	{Header: "Adjustment Klaim (Self Adjustment) OR", Field: "StatusClaim"},
	{Header: "Adjustment Klaim (Adjuster) OR", Field: "TelpTertanggung"},
	{Header: "Selisih Estimasi Klaim dengan Adjustment OR", Field: "UserAdmin"},
	{Header: "Nilai Salvage", Field: "RWID"},
	{Header: "Dokumen Penalti", Field: "ReporterTelp"},
	{Header: "Status Progress 1", Field: "AgingAmount"},
	{Header: "Status Progress 2", Field: "AlasanTerlambat"},
	{Header: "Tgl Terakhir Update Progress", Field: "ReceiverClaim"},
	{Header: "Jumlah FU Terlambat", Field: "ResponseNote"},
	{Header: "Jumlah Tidak FU Terlambat", Field: "StatusKomunikasi"},
	{Header: "Keterangan", Field: "pyNote"},
	{Header: "Sumber Bisnis", Field: "UserBusinessPA"},
	{Header: "Ceding/Leader", Field: "OwnRisk"},
	{Header: "Surveyor", Field: "SuspiciousComment"},
	{Header: "Loss Adjuster", Field: "StatusAnalystRemarks"},
	{Header: "Next Follow Up", Field: "StatusReceiver"},
	{Header: "Tgl Regist", Field: "NewNoKTP"},
	{Header: "Tgl Close Claim", Field: "NewEmail"},
	{Header: "Tgl Tf PIC", Field: "NewTelpTertanggung"},
	{Header: "Alasan Reject", Field: "AlasanDokterRejectRCL"},
	{Header: "Dominan Factor", Field: "DominanName"},
}

// colsAIKlaim — 14 kolom.
//
// Disalin dari `CSVProperties` dan `CSVPropHeaders` milik langkah
// `pxConvertResultsToCSV` pada `Activity/ExportHasilDataAIKlaim-Act.xml`.
var colsAIKlaim = []Column{
	{Header: "No Klaim", Field: "CaseID"},
	{Header: "No Polis", Field: "PolicyNo"},
	{Header: "Tertangung", Field: "City"},
	{Header: "Bisnis Name", Field: "CityID"},
	{Header: "Tgl Kejadian", Field: "NoKTP"},
	{Header: "Start Polis", Field: "CityID"},
	{Header: "End Polis", Field: "Country"},
	{Header: "ResultsAi", Field: "CountryID"},
	{Header: "Coverage AI Final", Field: "AlasanKlaim"},
	{Header: "Cause Of Los (AI)", Field: "NoteKasir"},
	{Header: "Coverage Kronologi (AI)", Field: "FlagASO"},
	{Header: "Tipe Note AI", Field: "NamaSurveyor"},
	{Header: "Note AI", Field: "DistrictID"},
	{Header: "", Field: "District"},
}
